### ISSUE TITLE
Assertion error while trying to create ROM dump for xaga 14.0.3TLOCNXM

### ISSUE THREAD

**Issue by avid-coder05** [AndroidDumps/dumpyara#52]
I encounter this error while running ./dumpyara.sh <file>

`Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/db-rom/dumpyara/.venv/lib/python3.9/site-packages/twrpdtgen/__main__.py", line 11, in <module>
    main()
  File "/home/db-rom/dumpyara/.venv/lib/python3.9/site-packages/twrpdtgen/main.py", line 37, in main
    device_tree = DeviceTree(image=args.image)
  File "/home/db-rom/dumpyara/.venv/lib/python3.9/site-packages/twrpdtgen/device_tree.py", line 66, in __init__
    self.device_info = DeviceInfo(self.build_prop)
  File "/home/db-rom/dumpyara/.venv/lib/python3.9/site-packages/sebaubuntu_libs/libandroid/device_info.py", line 117, in __init__
    self.codename = self.get_first_prop(DEVICE_CODENAME)
  File "/home/db-rom/dumpyara/.venv/lib/python3.9/site-packages/sebaubuntu_libs/libandroid/device_info.py", line 177, in get_first_prop
    raise AssertionError(f'Property {props[0]} could not be found in build.prop')
AssertionError: Property ro.product.bootimage.device could not be found in build.prop`

Is there any way to overcome this other than to manually change the files?

**Comment by avid-coder05** [comment]
The aospdt gen fails when running dumpyara for the above mentioned ROM

`[INFO] Figuring out partitions scheme
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/db-rom/dumpyara/.venv/lib/python3.9/site-packages/aospdtgen/__main__.py", line 11, in <module>
    main()
  File "/home/db-rom/dumpyara/.venv/lib/python3.9/site-packages/aospdtgen/main.py", line 31, in main
    dump = DeviceTree(args.dump_path)
  File "/home/db-rom/dumpyara/.venv/lib/python3.9/site-packages/aospdtgen/device_tree.py", line 36, in __init__
    self.partitions = Partitions(self.path)
  File "/home/db-rom/dumpyara/.venv/lib/python3.9/site-packages/sebaubuntu_libs/libandroid/partitions/partitions.py", line 25, in __init__
    self.partitions[PartitionModel.SYSTEM] = AndroidPartition(PartitionModel.SYSTEM, system)
  File "/home/db-rom/dumpyara/.venv/lib/python3.9/site-packages/sebaubuntu_libs/libandroid/partitions/partition.py", line 38, in __init__
    self.files = get_files_list(self.path)
  File "/home/db-rom/dumpyara/.venv/lib/python3.9/site-packages/sebaubuntu_libs/libandroid/partitions/partition.py", line 29, in get_files_list
    files.extend(get_files_list(i))
  File "/home/db-rom/dumpyara/.venv/lib/python3.9/site-packages/sebaubuntu_libs/libandroid/partitions/partition.py", line 25, in get_files_list
    for i in path.iterdir():
  File "/usr/lib/python3.9/pathlib.py", line 1149, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: 'system/system/product'
Failed to generate AOSP device tree
`

Also the super image wasn't extracted due to 'cannot find valid erofs superblock'
