### ISSUE TITLE
erofs problem

### ISSUE THREAD

**Issue by arsalan-zeus** [AndroidDumps/dumpyara#57]
script has one problem when i finds out that partitions are erofs thn while extracting it makes some  file shortcut links instead of copying file to that location. when you click on that file to show target then file manager isnt able to find out the file because its path is written as root. for example rm10proa41/system/system/etc/security/otacerts.zip here the dumpyara extracted it with fsck.erofs but in that location it is shortcut/link of the file otacerts.zip when you click on the link file to go for the target file it cant find it  because of wrong link location.
![image](https://github.com/AndroidDumps/dumpyara/assets/54109777/0705277d-9a00-43d3-b85e-6a5884127c80)
![image](https://github.com/AndroidDumps/dumpyara/assets/54109777/7b4c0c02-72c6-4d54-9acb-38096a63c857)
 see it does not able to find the path of file because path is set as root.
![image](https://github.com/AndroidDumps/dumpyara/assets/54109777/755530e2-e8ce-4420-9fcc-63e46f9cfd7b)
see here is file present in that directory where it is pointing but becaus of starting path is set as root it cant find it.
thats why here it gives error while generating dt.

python -m aospdtgen rm10proa41/
Android device tree generator
Version 1.0.0

[INFO] Figuring out partitions scheme
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/arsalan/.local/lib/python3.10/site-packages/aospdtgen/__main__.py", line 11, in <module>
    main()
  File "/home/arsalan/.local/lib/python3.10/site-packages/aospdtgen/main.py", line 31, in main
    dump = DeviceTree(args.dump_path)
  File "/home/arsalan/.local/lib/python3.10/site-packages/aospdtgen/device_tree.py", line 36, in __init__
    self.partitions = Partitions(self.path)
  File "/usr/local/lib/python3.10/dist-packages/sebaubuntu_libs/libandroid/partitions/partitions.py", line 25, in __init__
    self.partitions[PartitionModel.SYSTEM] = AndroidPartition(PartitionModel.SYSTEM, system)
  File "/usr/local/lib/python3.10/dist-packages/sebaubuntu_libs/libandroid/partitions/partition.py", line 38, in __init__
    self.files = get_files_list(self.path)
  File "/usr/local/lib/python3.10/dist-packages/sebaubuntu_libs/libandroid/partitions/partition.py", line 29, in get_files_list
    files.extend(get_files_list(i))
  File "/usr/local/lib/python3.10/dist-packages/sebaubuntu_libs/libandroid/partitions/partition.py", line 29, in get_files_list
    files.extend(get_files_list(i))
  File "/usr/local/lib/python3.10/dist-packages/sebaubuntu_libs/libandroid/partitions/partition.py", line 29, in get_files_list
    files.extend(get_files_list(i))
  File "/usr/local/lib/python3.10/dist-packages/sebaubuntu_libs/libandroid/partitions/partition.py", line 25, in get_files_list
    for i in path.iterdir():
  File "/usr/lib/python3.10/pathlib.py", line 1017, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: 'rm10proa41/system/system/etc/security/otacerts.zip'

please see through this issue deeply

**Comment by OneNormalUsername** [comment]
Not a dumpyara issue, closing.

**Comment by arsalan-zeus** [comment]
Sir 

> Not a dumpyara issue, closing.

Sir as it dumpyara uses fsck.erofs to handle erofs img but it creates wrong symbolic link / shortcut link of files.
