### ISSUE TITLE
AssertionError: Logical partition metadata has invalid geometry magic signature.

### ISSUE THREAD

**Issue by Fyramiz** [AndroidDumps/dumpyara#61]
Device:N-one(aka incar) npad air(codename NpadAir)
NOTE:i extracted pac file then made a zip out from it
Log:
Dumpyara
Version 1.0.2

[INFO] Step 1 - Extracting archive
[INFO] Step 2 - Preparing partition images
[INFO] Pattern *payload.bin* not found
[INFO] Found multipartition image: super.img
[INFO] Failed to unsparse super.img
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/3.12.1/bin/dumpyara", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dumpyara/main.py", line 40, in main
    output_path = dumpyara(args.file, output, args.debug)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dumpyara/dumpyara.py", line 33, in dumpyara
    step_2(extracted_archive_path, raw_images_path)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dumpyara/steps/step_2.py", line 43, in step_2
    func(multipart_image, raw_images_path)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dumpyara/utils/multipartitions.py", line 32, in extract_super
    lpunpack(image, output_dir)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/liblp/partition_tools/lpunpack.py", line 87, in lpunpack
    metadata = ReadMetadata(image, slot)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/liblp/reader.py", line 275, in ReadMetadata
    geometry = ReadLogicalPartitionGeometry(fd)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/liblp/reader.py", line 97, in ReadLogicalPartitionGeometry
    geometry = ReadPrimaryGeometry(fd)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/liblp/reader.py", line 84, in ReadPrimaryGeometry
    return ParseGeometry(buffer)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/liblp/reader.py", line 54, in ParseGeometry
    assert geometry.magic == LP_METADATA_GEOMETRY_MAGIC, \
AssertionError: Logical partition metadata has invalid geometry magic signature.

**Comment by ant14181** [comment]
> ```
> File "/workspace/.pyenv_mirror/user/3.12.1/bin/dumpyara", line 8, in
> sys.exit(main())
> ^^^^^^
> ```
Are you referencing to the Python rewrite of this project ([`SebaUbuntu-python/dumpyara`](https://github.com/sebaubuntu-python/dumpyara))? Note that said rewrite does not have full support for _all_ possible archives (in your case, `.pac`), hence the reason why it failed here.
